[observer]
# Coordonnées géographiques de l'observatoire / lieu d'observation
# latitude  : degrés décimaux, positif = Nord, négatif = Sud
# longitude : degrés décimaux, positif = Est,  négatif = Ouest
# elevation : altitude en mètres au-dessus du niveau de la mer

latitude  = 42.935589
longitude = 0.142586
elevation = 2880

# Nom libre pour l'affichage (optionnel)
name = Pic du Midi
